# Generated by Django 4.1.3 on 2023-01-10 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_bid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bid',
            old_name='current_bid',
            new_name='old_bid',
        ),
    ]
