# Generated by Django 4.1.3 on 2023-01-17 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0015_remove_auctionlisting_isactive_listing_isactive'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bid',
            name='old_bid',
        ),
        migrations.AlterField(
            model_name='bid',
            name='bid_amount',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='bid',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bid_item', to='auctions.listing'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='url',
            field=models.URLField(default='https://us.123rf.com/450wm/pavelstasevich/pavelstasevich1811/pavelstasevich181101027/pavelstasevich181101027.jpg', max_length=400),
        ),
        migrations.DeleteModel(
            name='AuctionListing',
        ),
    ]
