# Generated by Django 4.1.7 on 2023-05-03 06:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0018_alter_listing_description_alter_listing_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="watchlist",
            name="items",
            field=models.ManyToManyField(to="auctions.bid"),
        ),
    ]
