# Generated by Django 4.1.7 on 2023-05-04 06:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0021_alter_watchlist_items"),
    ]

    operations = [
        migrations.AlterField(
            model_name="watchlist",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="watcher",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
