# Generated by Django 4.1.7 on 2023-05-05 07:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0022_alter_watchlist_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="bid",
            name="highest_bid",
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
