# Generated by Django 4.1.7 on 2023-05-06 08:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0024_alter_comment_listing"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="created_at",
            field=models.DateTimeField(),
        ),
    ]
