# Generated by Django 4.1.7 on 2023-05-06 11:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0025_alter_comment_created_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bid",
            name="highest_bid",
        ),
    ]
