# Generated by Django 4.1.3 on 2023-01-04 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='bid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_bid', models.IntegerField(max_length=60)),
                ('new_bid', models.IntegerField(max_length=60)),
            ],
        ),
    ]
