# Generated by Django 4.1.3 on 2023-01-10 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_auctionlisting_remove_bid_old_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionlisting',
            name='isActive',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='auctionlisting',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='active_items', to='auctions.listing'),
        ),
        migrations.AddField(
            model_name='auctionlisting',
            name='price',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='active_bids', to='auctions.bid'),
        ),
        migrations.AddField(
            model_name='bid',
            name='old_amount',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
