# Generated by Django 4.1.3 on 2023-01-10 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0014_watchlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auctionlisting',
            name='price',
        ),
    ]
