# Generated by Django 4.1.3 on 2023-01-11 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0016_watchlist_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bid',
            name='old_amount',
        ),
    ]
