# Generated by Django 4.1.7 on 2023-05-04 05:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0019_alter_watchlist_items"),
    ]

    operations = [
        migrations.AlterField(
            model_name="watchlist",
            name="items",
            field=models.ManyToManyField(blank=True, to="auctions.bid"),
        ),
    ]
