# Generated by Django 4.1.7 on 2023-05-06 11:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0026_remove_bid_highest_bid"),
    ]

    operations = [
        migrations.AddField(
            model_name="bid",
            name="bid_starting_amt",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
