# Generated by Django 4.1.7 on 2023-05-06 12:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0027_bid_bid_starting_amt"),
    ]

    operations = [
        migrations.AddField(
            model_name="bid",
            name="isFinished",
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
